<a href="https://colab.research.google.com/github/StillWork/ds-lab/blob/master/gg_50_MNIST_%ED%85%90%EC%84%9C%ED%94%8C%EB%A1%9C%EC%9A%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# 단층 퍼셉트론으로 구축하기
# 성능이 80% 정도 나온다
import tensorflow as tf
from tensorflow.examples.tutorials.mnist import input_data

#원핫 인코딩을 선택한다
mnist_data = input_data.read_data_sets('MNIST_data', one_hot=True)

Extracting MNIST_data\train-images-idx3-ubyte.gz
Extracting MNIST_data\train-labels-idx1-ubyte.gz
Extracting MNIST_data\t10k-images-idx3-ubyte.gz
Extracting MNIST_data\t10k-labels-idx1-ubyte.gz


In [44]:
type(mnist_data)

tensorflow.contrib.learn.python.learn.datasets.base.Datasets

In [4]:
input_size = 784
no_classes = 10
batch_size = 100
total_batches = 200

# None은 임의의 크기를 담을 수 있다는 것을 말한다
x_input = tf.placeholder(tf.float32, shape=[None, input_size])
y_input = tf.placeholder(tf.float32, shape=[None, no_classes])

weights = tf.Variable(tf.random_normal([input_size, no_classes]))
bias = tf.Variable(tf.random_normal([no_classes]))
logits = tf.matmul(x_input, weights) + bias

Instructions for updating:
Colocations handled automatically by placer.


In [7]:
x_input.shape, weights.shape, y_input.shape

(TensorShape([Dimension(None), Dimension(784)]),
 TensorShape([Dimension(784), Dimension(10)]),
 TensorShape([Dimension(None), Dimension(10)]))

In [8]:
# 크로스엔트로피와 소프트맥스를 사용한다
# 손실함수와, 최적화기를 선택
# 학습속도 0.5
# softmax_cross_entropy(): Computes softmax cross entropy between logits and labels.
softmax_cross_entropy = tf.nn.softmax_cross_entropy_with_logits(
    labels=y_input, logits=logits)
loss_operation = tf.reduce_mean(softmax_cross_entropy)
optimiser = tf.train.GradientDescentOptimizer(
    learning_rate=0.5).minimize(loss_operation)

# 초기화
session = tf.Session()
session.run(tf.global_variables_initializer())

# 배치 작업 수행 
# feed_dict 인자에 훈련 데이터 딕셔너리를 공급
for batch_no in range(total_batches):
    mnist_batch = mnist_data.train.next_batch(batch_size)
    train_images, train_labels = mnist_batch[0], mnist_batch[1]
    _, loss_value = session.run([optimiser, loss_operation], feed_dict={
        x_input: train_images,
        y_input: train_labels
    })

Instructions for updating:

Future major versions of TensorFlow will allow gradients to flow
into the labels input on backprop by default.

See `tf.nn.softmax_cross_entropy_with_logits_v2`.



In [9]:
# weights.shape
# session.run(bias)
# session.run(weights).shape
# x_input.shape, weights.shape, y_input.shape
# x_input,  weights, y_input
# train_images.shape, train_labels.shape
# session.run(logits, feed_dict={x_input: train_images})
# session.run(logits, feed_dict={x_input: train_images})

In [10]:
# added for debugging
print ('bias is: ',session.run(bias))
print('weights are: ',session.run(weights))
print('logits are: ', session.run(logits, feed_dict={x_input: train_images}))

bias is:  [ 0.34358343 -1.9445122   0.44923887 -0.796643    0.36187997  0.26429063
 -1.1839765   1.094068   -1.2625928  -0.15602611]
weights are:  [[-0.9444775   0.0788077   1.5823524  ... -1.2135105  -1.7233548
   0.41759062]
 [-0.15141462 -1.2825084  -0.5807093  ... -0.4769059   0.09513462
  -0.5595411 ]
 [ 0.5083344   0.39757812 -0.01441983 ...  0.332977    0.4803232
   0.60378677]
 ...
 [ 1.7573912   1.4240342   0.36368108 ... -1.6863295   1.2776196
  -0.48303252]
 [ 0.7088426   0.89132774  1.5045044  ...  0.04421584 -0.27674192
  -1.2953362 ]
 [ 1.2624115  -0.2700953  -0.00551114 ... -0.36051124 -0.1901838
  -0.06977901]]
logits are:  [[ 5.50424719e+00 -2.24530506e+00 -8.23649406e+00  3.56332850e+00
  -3.34962368e+00  1.47562809e+01 -7.26106787e+00 -3.82548571e+00
   5.98326540e+00 -4.80786800e+00]
 [ 1.81688633e+01 -2.56401329e+01 -1.30547228e+01 -5.32935238e+00
  -6.99841642e+00  1.82321796e+01 -9.43886089e+00 -1.38561211e+01
   8.70768356e+00 -1.91372089e+01]
 [ 7.77394009e+00 

In [11]:
logits

<tf.Tensor 'add:0' shape=(?, 10) dtype=float32>

In [12]:
y_input

<tf.Tensor 'Placeholder_1:0' shape=(?, 10) dtype=float32>

In [13]:
predictions = tf.argmax(logits, 1)

correct_predictions = tf.equal(predictions, tf.argmax(y_input, 1))
accuracy_operation = tf.reduce_mean(tf.cast(correct_predictions,
                                            tf.float32))
test_images, test_labels = mnist_data.test.images, mnist_data.test.labels
accuracy_value = session.run(accuracy_operation, feed_dict={
    x_input: test_images,
    y_input: test_labels
})
print('Accuracy : ', accuracy_value)
session.close()

Accuracy :  0.8084


In [19]:
!pip install sklearn

  Created wheel for sklearn: filename=sklearn-0.0-py2.py3-none-any.whl size=1321 sha256=ddb0f003047743ca3ba12bc0347ebc3849c7d6a82f1c5b2335aa1473f9afddd8
  Stored in directory: C:\Users\rta_note\AppData\Local\pip\Cache\wheels\76\03\bb\589d421d27431bcd2c6da284d5f2286c8e3b2ea3cf1594c074
Successfully built sklearn


In [20]:
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
X = mnist_data.train.images
y = mnist_data.train.labels
rfc = RandomForestClassifier(n_estimators=50)
rfc.fit(X,y)
rfc.score(mnist_data.test.images, mnist_data.test.labels)

0.8968

In [21]:
mnist_data.train.images.shape, mnist_data.train.labels.shape

((55000, 784), (55000, 10))

In [22]:
mnist_data.train.labels[0]

array([0., 0., 0., 1., 0., 0., 0., 0., 0., 0.])

# Exercise

In [23]:
# 2-D tensor `a`
# [[1, 2, 3],
#  [4, 5, 6]]
a = tf.constant([1, 2, 3, 4, 5, 6], shape=[2, 3])

# 2-D tensor `b`
# [[ 7,  8],
#  [ 9, 10],
#  [11, 12]]
b = tf.constant([7, 8, 9, 10, 11, 12], shape=[3, 2])

# `a` * `b`
# [[ 58,  64],
#  [139, 154]]
c = tf.matmul(a, b)

In [26]:
tf.Session().run(c)

array([[ 58,  64],
       [139, 154]])

In [28]:
import numpy as np
# 3-D tensor `a`
# [[[ 1,  2,  3],
#   [ 4,  5,  6]],
#  [[ 7,  8,  9],
#   [10, 11, 12]]]
a = tf.constant(np.arange(1, 13, dtype=np.int32),
                shape=[2, 2, 3])

# 3-D tensor `b`
# [[[13, 14],
#   [15, 16],
#   [17, 18]],
#  [[19, 20],
#   [21, 22],
#   [23, 24]]]
b = tf.constant(np.arange(13, 25, dtype=np.int32),
                shape=[2, 3, 2])

# `a` * `b`
# [[[ 94, 100],
#   [229, 244]],
#  [[508, 532],
#   [697, 730]]]
c = tf.matmul(a, b)

In [29]:
tf.Session().run(a)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [31]:
tf.Session().run(b)

array([[[13, 14],
        [15, 16],
        [17, 18]],

       [[19, 20],
        [21, 22],
        [23, 24]]])

In [34]:
tf.Session().run(c)

array([[[ 94, 100],
        [229, 244]],

       [[508, 532],
        [697, 730]]])

In [35]:
a,b,c

(<tf.Tensor 'Const_4:0' shape=(2, 2, 3) dtype=int32>,
 <tf.Tensor 'Const_5:0' shape=(2, 3, 2) dtype=int32>,
 <tf.Tensor 'MatMul_2:0' shape=(2, 2, 2) dtype=int32>)

In [39]:
A = tf.Variable(tf.random_normal([5, 4, 10, 2, 3]))
B = tf.Variable(tf.random_normal([5, 4, 10, 3, 7]))
C = tf.matmul(A, B)

# tf.matmul(3차원 이상의 텐서 사이의 행렬 곱은 행렬의 차원을 나타내는 마지막 두 개의 
# 차원(2x3, 3x7) 사이에 행렬 곱이 가능하고 행렬 앞에 있는 차원(5x4x10)이 같으면 
# 가능한 것을 알 수 있습니다.
# 출처: https://bowbowbow.tistory.com/27 [멍멍멍]

In [43]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())
sess.run(C)
A.shape, B.shape, C.shape

(TensorShape([Dimension(5), Dimension(4), Dimension(10), Dimension(2), Dimension(3)]),
 TensorShape([Dimension(5), Dimension(4), Dimension(10), Dimension(3), Dimension(7)]),
 TensorShape([Dimension(5), Dimension(4), Dimension(10), Dimension(2), Dimension(7)]))