<a href="https://colab.research.google.com/github/StillWork/c9/blob/master/gg_67_%EB%8B%A8%EC%96%B4%EB%B2%A1%ED%84%B0_IMDB.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 단어 임베딩
### Embedding 계층을 사용하여 쉽게 만들 수 있다
- 정수 인덱스를 벡터로 매핑하는 딕셔너리 구조 (인덱스 크기, 벡터 크기)
- 학습 시키는 데이터에 따라 다른 임베딩이 만들어진다.

### IMDB 영화 리뷰 데이터를 사용한 임베딩 예제



In [1]:
from keras.models import Sequential
from keras.layers import Flatten, Dense, Embedding
import os, os.path
import zipfile
from keras.datasets import imdb
from keras import preprocessing
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

- 10000 개의 단어만 사용하고, 각 문장에서는 뒤에서부터 20 개의 단어만 사용하겠음.

In [2]:
max_features = 10000
maxlen = 20
(x_train, y_train), (x_test, y_test) = imdb.load_data(num_words=max_features)

17465344/17464789 [==============================] - 0s 0us/step


In [12]:
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((25000,), (25000,), (25000,), (25000,))

In [16]:
y_train[:5]

array([1, 0, 0, 1, 0])

In [5]:
[len(x_train[i]) for i in range(10)]

[218, 189, 141, 550, 147, 43, 123, 562, 233, 130]

In [6]:
# 각 문장이 몇개의 단어로 구성되어 있는지 확인
for i in range(10):
    print(len(x_train[i]))

218
189
141
550
147
43
123
562
233
130


In [7]:
x_train[0:2]   # words tokenized and expressed by (word) numbers

array([list([1, 14, 22, 16, 43, 530, 973, 1622, 1385, 65, 458, 4468, 66, 3941, 4, 173, 36, 256, 5, 25, 100, 43, 838, 112, 50, 670, 2, 9, 35, 480, 284, 5, 150, 4, 172, 112, 167, 2, 336, 385, 39, 4, 172, 4536, 1111, 17, 546, 38, 13, 447, 4, 192, 50, 16, 6, 147, 2025, 19, 14, 22, 4, 1920, 4613, 469, 4, 22, 71, 87, 12, 16, 43, 530, 38, 76, 15, 13, 1247, 4, 22, 17, 515, 17, 12, 16, 626, 18, 2, 5, 62, 386, 12, 8, 316, 8, 106, 5, 4, 2223, 5244, 16, 480, 66, 3785, 33, 4, 130, 12, 16, 38, 619, 5, 25, 124, 51, 36, 135, 48, 25, 1415, 33, 6, 22, 12, 215, 28, 77, 52, 5, 14, 407, 16, 82, 2, 8, 4, 107, 117, 5952, 15, 256, 4, 2, 7, 3766, 5, 723, 36, 71, 43, 530, 476, 26, 400, 317, 46, 7, 4, 2, 1029, 13, 104, 88, 4, 381, 15, 297, 98, 32, 2071, 56, 26, 141, 6, 194, 7486, 18, 4, 226, 22, 21, 134, 476, 26, 480, 5, 144, 30, 5535, 18, 51, 36, 28, 224, 92, 25, 104, 4, 226, 65, 16, 38, 1334, 88, 12, 16, 283, 5, 16, 4472, 113, 103, 32, 15, 16, 5345, 19, 178, 32]),
       list([1, 194, 1153, 194, 8255, 78, 228,

In [8]:
# 마지막 20개의 단어들만 사용한다. -> 20개보다 적으면 똑같은 길이로 만들어 준다. padding position is 'post'
x_train_p=preprocessing.sequence.pad_sequences(x_train, maxlen=maxlen, padding='post')
x_test_p=preprocessing.sequence.pad_sequences(x_test, maxlen=maxlen, padding='post')

In [9]:
x_train_p[0:2]

array([[  65,   16,   38, 1334,   88,   12,   16,  283,    5,   16, 4472,
         113,  103,   32,   15,   16, 5345,   19,  178,   32],
       [  23,    4, 1690,   15,   16,    4, 1355,    5,   28,    6,   52,
         154,  462,   33,   89,   78,  285,   16,  145,   95]],
      dtype=int32)

In [17]:
model = Sequential()
model.add(Embedding(10000, 8, input_length=maxlen))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))

model.compile(loss='binary_crossentropy',
              optimizer='rmsprop',
              metrics=['acc'])
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_2 (Embedding)      (None, 20, 8)             80000     
_________________________________________________________________
flatten_2 (Flatten)          (None, 160)               0         
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 161       
Total params: 80,161
Trainable params: 80,161
Non-trainable params: 0
_________________________________________________________________


In [18]:
history = model.fit(x_train_p, y_train,
                    epochs=10, batch_size=32,
                    validation_split=0.2)

Epoch 1/10
625/625 [==============================] - 2s 3ms/step - loss: 0.6717 - acc: 0.6120 - val_loss: 0.6233 - val_acc: 0.6926
Epoch 2/10
625/625 [==============================] - 2s 3ms/step - loss: 0.5443 - acc: 0.7501 - val_loss: 0.5288 - val_acc: 0.7282
Epoch 3/10
625/625 [==============================] - 2s 3ms/step - loss: 0.4627 - acc: 0.7886 - val_loss: 0.5028 - val_acc: 0.7430
Epoch 4/10
625/625 [==============================] - 2s 3ms/step - loss: 0.4221 - acc: 0.8105 - val_loss: 0.4980 - val_acc: 0.7502
Epoch 5/10
625/625 [==============================] - 2s 3ms/step - loss: 0.3948 - acc: 0.8253 - val_loss: 0.4958 - val_acc: 0.7556
Epoch 6/10
625/625 [==============================] - 2s 3ms/step - loss: 0.3718 - acc: 0.8387 - val_loss: 0.4996 - val_acc: 0.7584
Epoch 7/10
625/625 [==============================] - 2s 3ms/step - loss: 0.3513 - acc: 0.8507 - val_loss: 0.5060 - val_acc: 0.7522
Epoch 8/10
625/625 [==============================] - 2s 3ms/step - loss: 0.

## 위의 결과는 20개의 단어만 고려한 것임
### 성능이 75% 정도 됨
- 각 단어를 독립적으로 다루었으며, 문장의 구성 정보를 고려하지 않음
- 문장의 구조 정보를 고려하려면 임베딩 층 위에 합성곱이나 순환신경망 층을 추가한다

## RNN 추가

In [56]:
x_train_p.shape

(25000, 20)

In [70]:
from keras.models import Sequential
from keras.layers import SimpleRNN, Dense

model = Sequential()
model.add(Embedding(input_dim=10000, output_dim=8))
model.add(SimpleRNN(128))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))

model.compile(loss='binary_crossentropy',
              optimizer='rmsprop',
              metrics=['acc'])
model.summary()

Model: "sequential_7"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_8 (Embedding)      (None, None, 8)           80000     
_________________________________________________________________
simple_rnn_3 (SimpleRNN)     (None, 128)               17536     
_________________________________________________________________
flatten_6 (Flatten)          (None, 128)               0         
_________________________________________________________________
dense_6 (Dense)              (None, 1)                 129       
Total params: 97,665
Trainable params: 97,665
Non-trainable params: 0
_________________________________________________________________


In [72]:
history = model.fit(x_train_p, y_train,
                    epochs=20, batch_size=32,
                    validation_split=0.2)

Epoch 1/20
625/625 [==============================] - 7s 11ms/step - loss: 0.2366 - acc: 0.9054 - val_loss: 0.6656 - val_acc: 0.7322
Epoch 2/20
625/625 [==============================] - 7s 11ms/step - loss: 0.2135 - acc: 0.9142 - val_loss: 0.7111 - val_acc: 0.7404
Epoch 3/20
625/625 [==============================] - 7s 11ms/step - loss: 0.1929 - acc: 0.9262 - val_loss: 0.7477 - val_acc: 0.7168
Epoch 4/20
625/625 [==============================] - 7s 11ms/step - loss: 0.1761 - acc: 0.9305 - val_loss: 0.7536 - val_acc: 0.7054
Epoch 5/20
625/625 [==============================] - 7s 11ms/step - loss: 0.1596 - acc: 0.9385 - val_loss: 0.7384 - val_acc: 0.7302
Epoch 6/20
625/625 [==============================] - 7s 12ms/step - loss: 0.1452 - acc: 0.9440 - val_loss: 0.8054 - val_acc: 0.7122
Epoch 7/20
625/625 [==============================] - 7s 11ms/step - loss: 0.1330 - acc: 0.9502 - val_loss: 0.8328 - val_acc: 0.7230
Epoch 8/20
625/625 [==============================] - 7s 11ms/step - 

# 연습

In [19]:
import tensorflow as tf
# 문장 토큰화와 단어 토큰화
text=[['Hope', 'to', 'see', 'you', 'soon'],['Nice', 'to', 'see', 'you', 'again']]

# 각 단어에 대한 정수 인코딩
text=[[0, 1, 2, 3, 4],[5, 1, 2, 3, 6]]

# 위 데이터가 아래의 임베딩 층의 입력이 된다.
embedding_layer = Embedding(7, 2, input_length=5)
result = embedding_layer(tf.constant([0, 1, 2, 3, 4, 5, 6]))
print(result.numpy())

# 7은 단어의 개수. 즉, 단어 집합(vocabulary)의 크기이다.
# 2는 임베딩한 후의 벡터의 크기이다.
# 5는 각 입력 시퀀스의 길이. 즉, input_length이다. 아래와 같은 형태가 됨.


[[-0.02118009 -0.00927242]
 [ 0.02958209 -0.00727258]
 [-0.02273032  0.04170969]
 [-0.03339268 -0.00979058]
 [-0.046245   -0.01901625]
 [ 0.01861269 -0.0196162 ]
 [ 0.00043071  0.04945743]]


In [32]:
from sklearn.feature_extraction.text import CountVectorizer

corpus = ['Hope to see you soon',
         'Nice to see you again']
cv = CountVectorizer()
cv.fit_transform(corpus).toarray() , cv.get_feature_names(), cv.vocabulary_

(array([[0, 1, 0, 1, 1, 1, 1],
        [1, 0, 1, 1, 0, 1, 1]]),
 ['again', 'hope', 'nice', 'see', 'soon', 'to', 'you'],
 {'again': 0, 'hope': 1, 'nice': 2, 'see': 3, 'soon': 4, 'to': 5, 'you': 6})

In [39]:
from gensim.models.word2vec import Word2Vec

text=[['Hope', 'to', 'see', 'you', 'soon'],
      ['Nice', 'to', 'see', 'you', 'again']]

model = Word2Vec(text, min_count=1, size=2)

In [54]:
for i in range(len(text)):
    print(model[text[i]])

[[ 0.23368882  0.09553892]
 [-0.13342807  0.19152431]
 [-0.21259055 -0.11372297]
 [-0.12717737 -0.15141335]
 [ 0.06255915  0.16907026]]
[[ 0.0576661  -0.07021116]
 [-0.13342807  0.19152431]
 [-0.21259055 -0.11372297]
 [-0.12717737 -0.15141335]
 [-0.16266923  0.08115795]]


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
  
